name: Run unit tests
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          pod install
          ./run-tests-with-api-key.sh ${{ secrets.API_KEY }}
